export const CATEGORIES = [
  { id: 'Salary / Income',      name: 'Salary / Income',      color: '#2E7D55', icon: '💰' },
  { id: 'Income Tax',           name: 'Income Tax',           color: '#BD4B2E', icon: '🏛' },
  { id: 'Credit Card Payment',  name: 'Credit Card Payment',  color: '#1C5B79', icon: '💳' },
  { id: 'Bank Interest',        name: 'Bank Interest',        color: '#2E7D55', icon: '🏦' },
  { id: 'Rent',                 name: 'Rent',                 color: '#7A7164', icon: '🏠' },
  { id: 'Investment',           name: 'Investment',           color: '#1C5B79', icon: '📈' },
  { id: 'Food & Dining',        name: 'Food & Dining',        color: '#BD4B2E', icon: '🍽' },
  { id: 'Shopping',             name: 'Shopping',             color: '#A9772E', icon: '🛍' },
  { id: 'Bills & Utilities',    name: 'Bills & Utilities',    color: '#1C5B79', icon: '💡' },
  { id: 'Fuel',                 name: 'Fuel',                 color: '#7A7164', icon: '⛽' },
  { id: 'Travel & Transport',   name: 'Travel & Transport',   color: '#1C5B79', icon: '🚕' },
  { id: 'Insurance',            name: 'Insurance',            color: '#7A7164', icon: '🛡' },
  { id: 'Subscriptions',        name: 'Subscriptions',        color: '#A9772E', icon: '📱' },
  { id: 'ATM / Cash',           name: 'ATM / Cash',           color: '#7A7164', icon: '🏧' },
  { id: 'Bank Transfer',        name: 'Bank Transfer',        color: '#7A7164', icon: '↔' },
  { id: 'UPI Payment',          name: 'UPI Payment',          color: '#A9772E', icon: '📲' },
  { id: 'Uncategorized',        name: 'Uncategorized',        color: '#C7BDAA', icon: '📦' },
];
export const catById = Object.fromEntries(CATEGORIES.map(c => [c.id, c]));
